//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRent.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rentalEntities1 : DbContext
    {
        public rentalEntities1()
            : base("name=rentalEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Insurance> Insurance { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Rentals> Rentals { get; set; }
        public virtual DbSet<Reservations> Reservations { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<VehicleFeatures> VehicleFeatures { get; set; }
        public virtual DbSet<VehicleFeaturesDetails> VehicleFeaturesDetails { get; set; }
        public virtual DbSet<VehicleImages> VehicleImages { get; set; }
        public virtual DbSet<VehicleReviews> VehicleReviews { get; set; }
        public virtual DbSet<Vehicles> Vehicles { get; set; }
        public virtual DbSet<VehicleType> VehicleType { get; set; }
    }
}
