//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleFeaturesDetails
    {
        public int VehicleID { get; set; }
        public int FeatureID { get; set; }
        public string detailDescription { get; set; }
    
        public virtual VehicleFeatures VehicleFeatures { get; set; }
        public virtual Vehicles Vehicles { get; set; }
    }
}
