//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleReviews
    {
        public int ReviewID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public string ReviewText { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Vehicles Vehicles { get; set; }
    }
}
